// 07-cadastro-simples.alg
// Exemplo de cadastro simples no Visualg
// Disciplina: Algoritmos e Lógica de Programação I
// Professor: Edson Orivaldo Lessa Junior

algoritmo "CadastroSimples"
var
   nome: caractere
   idade: inteiro
inicio
   escreva("Nome: ")
   leia(nome)
   escreva("Idade: ")
   leia(idade)
   escreval("Cadastro realizado!")
   escreval("Nome: ", nome)
   escreval("Idade: ", idade)
fimalgoritmo
